version: '3.8'

services:
  zabbix-switch-api:
    container_name: zabbix-switch-api
    build:
        context: ../../
        dockerfile: ./.docker/php/Dockerfile
    volumes:
            - ../../:/var/www/html
    ports:
      - 80:80
    restart: unless-stopped
