version: '3.8'

services:
  zabbix-switch-api:
    container_name: zabbix-switch-api
    build:
      context: ../../
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
