version: '3.3'

services:
  zabbix-switch-api:
    container_name: zabbix-switch-api
    build:
      context: ../../
      dockerfile: ./.docker/php/Dockerfile
    ports:
      - 81:81
    restart: unless-stopped
